spring.application.name=release-mail-generator
openai.api.key=${OPENAI_API_KEY:}
openai.api.url=https://api.groq.com/openai/v1/chat/completions
openai.model=llama-3.3-70b-versatile
server.port=${PORT:8080}
